---
# Ryan Cheevers-Brown, 2022-09-09, rfc6058@rit.edu
- name: "win ping test"
  hosts: windows
  become: false
  gather_facts: false

  tasks:

    - name: "test reachability"
      win_ping:

    - name: Create temp directory for deployments
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: "Deploy 7-zip to Windows host"
      win_get_url:
        url: https://www.7-zip.org/a/7z2201-x64.msi
        dest: C:\temp\7zip.msi

    - name: execute msi
      win_package:
        path: C:\temp\7zip.msi

    