---
# Ryan Cheevers-Brown, 2022-09-09, rfc6058@rit.edu
- name: "win ping test"
  hosts: windows
  become: false
  gather_facts: false

  tasks:

<<<<<<< HEAD
    - name: "Test Reachability"
      win_ping:

    - name: "Install Prerequisites - C++ 2015 Redistributable"
      ansible.windows.win_package:
        path: https://aka.ms/vs/17/release/vc_redist.x64.exe
        arguments: /q /norestart
        state: present
        product_id: 

    - name: "Install MySQL"
      ansible.windows.win_package:
        path: //URL to download here
        arguments: /q /norestart
        state: present
        product_id: //google
=======
    - name: "test reachability"
      win_ping:

    - name: Create temp directory for deployments
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: "Deploy 7-zip to Windows host"
      win_get_url:
        url: https://www.7-zip.org/a/7z2201-x64.msi
        dest: C:\temp\7zip.msi

    - name: execute msi
      win_package:
        path: C:\temp\7zip.msi

    
>>>>>>> f36d260a55cafd2758aaead8d10da94fd2010aa6
