---
- name: "win ping test"
  hosts: windows
  become: false
  gather_facts: false

  tasks:

    - name: "Test Reachability"
      win_ping:

    - name: "Install Prerequisites - C++ 2015 Redistributable"
      ansible.windows.win_package:
        path: https://aka.ms/vs/17/release/vc_redist.x64.exe
        arguments: /q /norestart
        state: present
        product_id: 

    - name: "Install MySQL"
      ansible.windows.win_package:
        path: //URL to download here
        arguments: /q /norestart
        state: present
        product_id: //google
