---
- hosts: pfsense
  become: true
  vars_files:
    - default.yml

  tasks:
    - name: "test connectivity" 
      ping:

    - name: "Set Dark Mode"
      pfsense_setup:
        webguicss: pfSense-dark

    - name: "Set WAN"


